### ISSUE TITLE
cvae_verification.py is not working 

### ISSUE THREAD

**Issue by kirimatt** [kstoneriv3/Fake-Voice_Detection#3]
Traceback (most recent call last):
  File "./src/verification_vae/cvae_verification.py", line 106, in <module>
    cvae['target'] = cvae_training(train_data['Verif_{}'.format(case)])
  File "D:\myenv\Fake-Voice-Detection-master\src\verification_vae\cvae_keras.py", line 150, in cvae_training
    vae.fit(x_train,x_train,epochs=epochs,steps_per_epoch=40)
  File "\lib\site-packages\keras\engine\training.py", line 1637, in fit
    batch_size=batch_size)
  File "\lib\site-packages\keras\engine\training.py", line 1483, in _standardize_user_data
    exception_prefix='input')
  File "\lib\site-packages\keras\engine\training.py", line 76, in _standardize_input_data
    data = [np.expand_dims(x, 1) if x is not None and x.ndim == 1 else x for x in data]
  File "\lib\site-packages\keras\engine\training.py", line 76, in <listcomp>
    data = [np.expand_dims(x, 1) if x is not None and x.ndim == 1 else x for x in data]
AttributeError: 'Tensor' object has no attribute 'ndim'

**Comment by kirimatt** [comment]
for computers without AVX one way to use older tensorflow, but this project use new features, so it has the only way to start, which is running on newer tensorflow without that issue.
